name: Release and Publish to Artifact Registry
on: workflow_dispatch
jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: git config
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: Setup Node from .nvmrc
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
      - name: Install dependencies with pnpm
        run: npm install -g pnpm@9.14.2
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Release with release-it
        run: pnpm release --ci --no-npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
